[package]
name = "counter-rs"
version = "0.1.0"
edition = "2024"


[workspace]

[dependencies]
anchor-client = { version = "0.31.1", features = ["async"] }
anchor-lang = "0.31.1"
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["full"] }
